spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  quartz:
    job-store-type: jdbc
    scheduler-name: QuackScheduler
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER}
    password: ${MAIL_APP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    com.pickax.status.page.server: debug

security:
  jwt-config:
    secret: "&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9"
    access-token-expire: 3600000

slack:
  token: ${BOT_USER_OAUTH_TOKEN}
  channel:
    monitor: '#error-quack-run'

#profiles:
#  name: ${ACTIVE_PROFILE}

